# Telegram credentials
TELEGRAM_TOKEN = "8060700030:AAEuKqli2hAld0wA7Eu-VA-mmNvBkJT_6bc"
CHAT_ID = "1379843400"

# Google service account credentials
[gcp_service_account]
type = "service_account"
project_id = "squashbuddies"
private_key_id = "6c6322e56f56defe4904aa327e2632ae36e38477"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDl60tQ7t9JWop1\nsqld9QHMQFE5hygFtr4wz8Va9sYrH7JfXziYRTk/O01pxnc2fjXS2I6khbENHyoQ\nb+j6HoueGANs03VLcCyq4/OiUTnBGeO9O/0c4ACK2jvrQrv+EZGn83LYdMumKJsB\n6eBa9+x2tHMfdxsS1HTe4XStHBg9Ywo1s2kbKPGl7WMnmbu+guK0dmfwBZf5Iqbg\nPq2EHYwdZPXVSgdXvFMPe/zB4TkGhVat9nxzuitTzBHfw4mmAiNXcFK/CPiy1Q88\n01TDrp1nR1eMsv8nDfXIXEtDcIVa+80hgbrAbPtmPA6lZExIVChTCsVIKdZrO1E1\nJcZ891uVAgMBAAECggEAFgOJdalrA257i4zJYgYhH6NyEEe5FMb4/qc+Fn+o3LZc\n...rest of key...\n-----END PRIVATE KEY-----\n"
client_email = "squash-buddies-service@squashbuddies.iam.gserviceaccount.com"
client_id = "101709777961912242471"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/squash-buddies-service%40squashbuddies.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
