# Telegram credentials
TELEGRAM_TOKEN = "8060700030:AAEuKqli2hAld0wA7Eu-VA-mmNvBkJT_6bc"
CHAT_ID = "1379843400"

# Google service account credentials
[gcp_service_account]
type = "service_account"
project_id = "squashbuddies"
private_key_id = "6c6322e56f56defe4904aa327e2632ae36e38477"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDl60tQ7t9JWop1...\n-----END PRIVATE KEY-----\n"
client_email = "squash-buddies-service@squashbuddies.iam.gserviceaccount.com"
client_id = "101709777961912242471"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/squash-buddies-service%40squashbuddies.iam.gserviceaccount.com"
