# Telegram credentials
TELEGRAM_TOKEN = "8060700030:AAEuKqli2hAld0wA7Eu-VA-mmNvBkJT_6bc"
CHAT_ID = "1379843400"

# Google service account credentials
[gcp_service_account]
type = "service_account"
project_id = "squashbuddies"
private_key_id = "6c6322e56f56defe4904aa327e2632ae36e38477"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDl60tQ7t9JWop1
sqld9QHMQFE5hygFtr4wz8Va9sYrH7JfXziYRTk/O01pxnc2fjXS2I6khbENHyoQ
b+j6HoueGANs03VLcCyq4/OiUTnBGeO9O/0c4ACK2jvrQrv+EZGn83LYdMumKJsB
6eBa9+x2tHMfdxsS1HTe4XStHBg9Ywo1s2kbKPGl7WMnmbu+guK0dmfwBZf5Iqbg
Pq2EHYwdZPXVSgdXvFMPe/zB4TkGhVat9nxzuitTzBHfw4mmAiNXcFK/CPiy1Q88
01TDrp1nR1eMsv8nDfXIXEtDcIVa+80hgbrAbPtmPA6lZExIVChTCsVIKdZrO1E1
JcZ891uVAgMBAAECggEAFgOJdalrA257i4zJYgYhH6NyEEe5FMb4/qc+Fn+o3LZc
HhaTaCNX0ygquTurH8wSYjduFof4bX20FnI1axFWo9+Mhs4LHbR5Vy/PnK7mdtWZ
2rBuNszZygtE9mywbEFvyHyeQxkq6iQnWnxAPEvsCtEsC3GCsmXy/k4btxSidR08
H5mSqh0xe23V+xx2iXJt46bljnEg8sbDX7FM2etwq3lTO6tcatu9lR+VgqhYxCsx
ZyGePKAQ2nHpD7nOIOtpHCUHYHxTACUGL2HzMlbjNMRRCgyJ5f/MdH9BFXHmSxHG
xCCDmDFzQVZPAwXh7JXgLp9f2ztTxq8l1cGTAfOWBwKBgQD1YMW65xSniVodJuad
lYyM0ul+6SH/5S17z69iY5ACmrYGi63eAj5K25LjVVbJG6e4PaQub3R22++iAwbY
yUu3IwbBJH0YSN2Y+LDvZVPaRKHGf6Fa/XU49cK5AZK6zDq3uqiE4jqZYj4R+ot5
MqN6fKeLj5y6bL6ea+juG3LgWwKBgQDv3zWlAyYEIoj5y5Rf/YnvZP8Qt5mLAI3P
VE4TseC8YE2zq6FW1aauU9LdAmhtbJELEKmvoYnJ4/jFQg4K+X5cltvxjf4zKBLb
M++zrw6AdCi+EHXH4Q4GJN8l6Vg/UjyMKbwUhRKrRaQMBr1J1dBGIFSoVbY8qP/G
mOBAtx52zwKBgQC5xY9Nxn9zq+Bmq7nzWnKzd0bCB5zvEMJTt1QQCFLSNfFTmVKD
/2zL3dsic8ylq2NacIipg0ZIapDNNr9rR1MkjschWQ/AYAItOzMxu6Q1Xrqf/qbZ
rYSfIClRSeidtdtKmG3XVTOKRr+5etc3Zegw5skuNwcweP4EEKykAHIDewKBgBT6
zNJV6ClMa/aNG7kZj8rkZnqr1D4YGk8b7IhEcoeHVMR2KnJR1XZB1puF7mRDrpvt
JSo7UrXZvpRiJqBHGgo3F52U8bq/soaBkGGC2h3aCwY0oliNEpDvAKVsN0+yfaE0
tUKGMQ/R03tJy5x9mu3HPiBK/tlnXpecH2EJoxx5AoGBANW67cj6XbpmfPm8rhFT
0uqmwUwQ6SZwpgvHwm9wQBkphW3J3CvIHd/M4LpiBtumDRtCs9D+sPh6mWbyLUkI
L5oGOQYgTMYsfFL4bvaGta3pRF8Ba68fyS5iXBetd/2Ho9DgbxI44xBPShkbrT9V
xoSWZ102tt0uIKs/B2Fjm84V
-----END PRIVATE KEY-----"""

client_email = "squash-buddies-service@squashbuddies.iam.gserviceaccount.com"
client_id = "101709777961912242471"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/squash-buddies-service%40squashbuddies.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
